definitions:
  dto.LinkDTO:
    properties:
      clicks:
        type: integer
      code:
        type: string
      createdAt:
        type: string
      lastClick:
        type: string
      link:
        type: string
      linkId:
        type: string
      url:
        type: string
    type: object
  request.RequestLink:
    properties:
      alias:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  response.LinkResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.LinkDTO'
        type: array
      isLastPage:
        type: boolean
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /{code}:
    get:
      description: Nhận mã short link và redirect người dùng đến URL gốc
      parameters:
      - description: Short link code
        in: path
        name: code
        required: true
        type: string
      responses:
        "302":
          description: Redirect đến URL gốc
        "404":
          description: Short link không tồn tại
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Chuyển hướng đến URL gốc bằng short link
      tags:
      - redirect
  /links:
    get:
      consumes:
      - application/json
      description: Lấy danh sách link theo phân trang và filter theo ngày (tuỳ chọn)
      parameters:
      - default: 1
        description: Trang hiện tại
        in: query
        name: page
        type: integer
      - default: 10
        description: Số item mỗi trang
        in: query
        name: limit
        type: integer
      - description: Ngày bắt đầu lọc (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: Ngày kết thúc lọc (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LinkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Lấy danh sách link
      tags:
      - links
    post:
      consumes:
      - application/json
      description: Generate a short URL from a long URL
      parameters:
      - description: URL to shorten
        in: body
        name: link
        required: true
        schema:
          $ref: '#/definitions/request.RequestLink'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - links
  /links/{id}:
    delete:
      description: Xóa một link dựa trên linkID và toàn bộ dữ liệu liên quan (như
        clicks)
      parameters:
      - description: Link ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: ID không hợp lệ hoặc thiếu ID
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Không tìm thấy link
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Lỗi hệ thống
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Xóa link theo ID
      tags:
      - links
    get:
      consumes:
      - application/json
      description: Trả về thông tin chi tiết của link dựa vào linkID
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Lấy thông tin link theo linkID
      tags:
      - links
    put:
      consumes:
      - application/json
      description: Cập nhật URL và alias của một link dựa theo linkID
      parameters:
      - description: Link ID (UUID)
        in: path
        name: id
        required: true
        type: string
      - description: Dữ liệu cập nhật link
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.RequestLink'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: URL hoặc alias không hợp lệ
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Link không tồn tại
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Lỗi hệ thống
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Cập nhật link
      tags:
      - links
  /links/link:
    get:
      consumes:
      - application/json
      description: Trả về thông tin chi tiết của link dựa vào short Link
      parameters:
      - description: Short Link
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Lấy thông tin link theo short Link
      tags:
      - links
swagger: "2.0"
