definitions:
  dto.LinkDTO:
    properties:
      clicks:
        type: integer
      code:
        type: string
      createdAt:
        type: string
      lastClick:
        type: string
      link:
        type: string
      linkId:
        type: string
      url:
        type: string
    type: object
  request.RequestLink:
    properties:
      url:
        type: string
    required:
    - url
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  response.LinkResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/dto.LinkDTO'
        type: array
      isLastPage:
        type: boolean
      limit:
        type: integer
      page:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
paths:
  /api/links:
    get:
      consumes:
      - application/json
      description: Lấy danh sách link theo phân trang
      parameters:
      - default: 1
        description: Trang hiện tại
        in: query
        name: page
        type: integer
      - default: 10
        description: Số item mỗi trang
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.LinkResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Lấy danh sách link
      tags:
      - links
    post:
      consumes:
      - application/json
      description: Generate a short URL from a long URL
      parameters:
      - description: URL to shorten
        in: body
        name: link
        required: true
        schema:
          $ref: '#/definitions/request.RequestLink'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a short link
      tags:
      - links
  /api/links/link:
    get:
      consumes:
      - application/json
      description: Trả về thông tin chi tiết của link dựa vào short Link
      parameters:
      - description: Short Link
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LinkDTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Lấy thông tin link theo short Link
      tags:
      - links
  /api/links/test:
    get:
      description: Test handler to check server
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Test API
      tags:
      - links
swagger: "2.0"
